CREATE TABLE STUDENT(Enrollment_No VARCHAR(20) , Name VARCHAR(25) , CPI DECIMAL(5,2) , Birthdate DATETIME)
SELECT * FROM STUDENT_MASTER


/*3.1*/   ALTER TABLE STUDENT ADD City VARCHAR(20) NULL , Backlog INT NOT NULL
/*3.2*/   ALTER TABLE STUDENT ALTER COLUMN Name VARCHAR(35)
/*3.3*/   ALTER TABLE STUDENT ALTER COLUMN CPI INT
/*3.4*/   SP_RENAME 'STUDENT.Enrollment_No' , 'ENO' , 'COLUMN'
/*3.5*/   ALTER TABLE STUDENT DROP COLUMN City
/*3.6*/   SP_RENAME 'STUDENT' , 'STUDENT_MASTER'
/*3.7*/   ALTER TABLE STUDENT_MASTER DROP COLUMN Backlog
/*3.8*/   ALTER TABLE STUDENT_MASTER ALTER COLUMN Name VARCHAR(35) NOT NULL
/*3.9*/   SP_RENAME 'STUDENT_MASTER.Birthdate' , 'BDATE' , 'COLUMN'
/*3.10*/  ALTER TABLE STUDENT_MASTER ALTER COLUMN ENO VARCHAR(12)
