--------------------------------------------------------------------STUDENT--------------------------------------------------------------------

CREATE TABLE STUDENT
(
	RNO INT NOT NULL,
	NAME VARCHAR(50),
	BRANCH VARCHAR(50)
)

INSERT INTO STUDENT VALUES
(101,'RAJU','CE'),
(102,'AMIT','CE'),
(103,'SANJAY','ME'),
(104,'NEHA','EC'),
(105,'MEERA','EE'),
(106,'MAHESH','ME')

--------------------------------------------------------------------RESULT--------------------------------------------------------------------

CREATE TABLE RESULT
(
	RNO INT NOT NULL,
	SPI DECIMAL(4,2) NOT NULL
)

INSERT INTO RESULT VALUES
(101,8.8),
(102,9.2),
(103,7.6),
(104,8.2),
(105,7.0),
(107,8.9)

------------------------------------------------------------------EMPLOYEE_NEW------------------------------------------------------------------

CREATE TABLE EMPLOYEE_NEW
(
	EMPLOYEENO VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	MANAGERNO VARCHAR(50) NULL
)

INSERT INTO EMPLOYEE_NEW VALUES
('E01','TARUN',NULL),
('E02','ROHAN','E02'),
('E03','PRIYA','E01'),
('E04','MILAN','E03'),
('E05','JAY','E01'),
('E06','ANJANA','E04')

--------------------------------------------------------------------PART-1--------------------------------------------------------------------

/*10.1.01*/     SELECT * FROM STUDENT CROSS JOIN RESULT    /*OR*/    SELECT * FROM STUDENT,RESULT

/*10.1.02*/     SELECT NAME,BRANCH,STUDENT.RNO,SPI FROM STUDENT LEFT OUTER JOIN RESULT ON STUDENT.RNO = RESULT.RNO WHERE STUDENT.BRANCH = 'CE'

/*10.1.03*/     SELECT NAME,BRANCH,STUDENT.RNO,SPI FROM STUDENT LEFT OUTER JOIN RESULT ON STUDENT.RNO = RESULT.RNO WHERE STUDENT.BRANCH <> 'EC'

/*10.1.04*/     SELECT BRANCH,AVG(RESULT.SPI) FROM STUDENT INNER JOIN RESULT ON STUDENT.RNO = RESULT.RNO GROUP BY BRANCH

/*10.1.05*/     SELECT BRANCH,AVG(RESULT.SPI) FROM STUDENT INNER JOIN RESULT ON STUDENT.RNO = RESULT.RNO GROUP BY BRANCH ORDER BY AVG(RESULT.SPI)

/*10.1.06*/     SELECT BRANCH,AVG(RESULT.SPI) FROM STUDENT INNER JOIN RESULT ON STUDENT.RNO = RESULT.RNO WHERE BRANCH IN ('CE','ME') GROUP BY BRANCH

/*10.1.07*/     SELECT * FROM STUDENT LEFT OUTER JOIN RESULT ON STUDENT.RNO = RESULT.RNO

/*10.1.08*/     SELECT * FROM STUDENT RIGHT OUTER JOIN RESULT ON STUDENT.RNO = RESULT.RNO

/*10.1.09*/     SELECT * FROM STUDENT FULL OUTER JOIN RESULT ON STUDENT.RNO = RESULT.RNO

/*10.1.10*/     SELECT E.NAME,M.NAME FROM EMPLOYEE_NEW E LEFT JOIN EMPLOYEE_NEW M ON E.MANAGERNO = M.EMPLOYEENO


--------------------------------------------------------------------PART-2--------------------------------------------------------------------


CREATE TABLE CITY
(
	CITYID INT PRIMARY KEY,
	CITYNAME VARCHAR(50) UNIQUE,
	PINCODE VARCHAR(6) NOT NULL,
	REMARKS VARCHAR(250)
)

INSERT INTO CITY VALUES
(1,'RAJKOT','360005','GOOD'),
(2,'SURAT','335009','VERY GOOD'),
(3,'BARODA','390001','AWESOME'),
(4,'JAMNAGAR','361003','SMART'),
(5,'JUNAGADH','362229','HISTORIC'),
(6,'MORBI','363641','CERAMIC')



CREATE TABLE VILLAGE
(
	VILLAGEID INT PRIMARY KEY,
	VILLAGENAME VARCHAR(50) NOT NULL,
	CITYID INT FOREIGN KEY REFERENCES CITY(CITYID)
)

INSERT INTO VILLAGE VALUES
(101,'RAIYA',1),
(102,'MADHAPAR',1),
(103,'DODKA',3),
(104,'FALLA',4),
(105,'BHESAN',5),
(106,'DHORAJI',5)


/*10.2.01*/       SELECT VILLAGE.VILLAGENAME,CITY.CITYNAME FROM CITY INNER JOIN VILLAGE ON CITY.CITYID = VILLAGE.CITYID WHERE CITY.CITYNAME = 'RAJKOT'

/*10.2.02*/       SELECT CITY.CITYNAME,CITY.PINCODE,VILLAGE.VILLAGENAME FROM CITY INNER JOIN VILLAGE ON CITY.CITYID = VILLAGE.CITYID

/*10.2.03*/       SELECT CITY.CITYNAME,COUNT(VILLAGE.VILLAGENAME) FROM CITY INNER JOIN VILLAGE ON CITY.CITYID = VILLAGE.CITYID GROUP BY CITY.CITYNAME HAVING COUNT(VILLAGE.VILLAGENAME) > 1

/*10.2.04*/       SELECT CITY.CITYNAME FROM CITY LEFT OUTER JOIN VILLAGE ON CITY.CITYID = VILLAGE.CITYID GROUP BY CITY.CITYNAME HAVING COUNT(VILLAGE.VILLAGENAME) = 0

/*10.2.05*/       SELECT CITY.CITYNAME,COUNT(VILLAGE.VILLAGENAME) NO_OF_VILLAGES FROM CITY LEFT OUTER JOIN VILLAGE ON CITY.CITYID = VILLAGE.CITYID GROUP BY CITY.CITYNAME

/*10.2.06*/       SELECT COUNT(COUNT(CITY.CITYNAME)) AS NO_OF_CITIES FROM CITY LEFT OUTER JOIN VILLAGE ON CITY.CITYID = VILLAGE.CITYID GROUP BY CITY.CITYNAME HAVING COUNT(VILLAGE.VILLAGENAME) > 1