----------------------------------------------------------------SET OPERATORS----------------------------------------------------------------


CREATE TABLE COMPUTER
(
	ROLLNO INT NOT NULL, 
	NAME VARCHAR(50) NOT NULL
)


CREATE TABLE ELECTRICAL
(
	ROLLNO INT NOT NULL, 
	NAME VARCHAR(50) NOT NULL
)


INSERT INTO COMPUTER VALUES
(101,'AJAY'),
(109,'HARESH'),
(115,'MANISH')


INSERT INTO ELECTRICAL VALUES
(105,'AJAY'),
(107,'MAHESH'),
(115,'MANISH')


/*9.1.01*/     SELECT NAME FROM COMPUTER UNION SELECT NAME FROM ELECTRICAL

/*9.1.02*/     SELECT NAME FROM COMPUTER UNION ALL SELECT NAME FROM ELECTRICAL

/*9.1.03*/     SELECT NAME FROM COMPUTER INTERSECT SELECT NAME FROM ELECTRICAL

/*9.1.04*/     SELECT NAME FROM COMPUTER EXCEPT SELECT NAME FROM ELECTRICAL

/*9.1.05*/     SELECT NAME FROM ELECTRICAL EXCEPT SELECT NAME FROM COMPUTER

/*9.1.06*/     SELECT * FROM COMPUTER UNION SELECT * FROM ELECTRICAL

/*9.1.07*/     SELECT * FROM COMPUTER INTERSECT SELECT * FROM ELECTRICAL


--------------------------------------------------------------------INTO--------------------------------------------------------------------

CREATE TABLE CRICKET
(
	NAME VARCHAR(50) NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	AGE INT NOT NULL
)


INSERT INTO CRICKET VALUES
('SACHIN TENDULKAR','MUMBAI',30),
('RAHUL DRAVID','BOMBAY',35),
('M.S.DHONI','JHARKHAND',31),
('SURESH RAINA','GUJARAT',30)


/*9.2.01*/     SELECT * INTO WORLD_CUP FROM CRICKET

/*9.2.02*/     SELECT NAME,CITY INTO T20 FROM CRICKET WHERE 1 = 2

/*9.2.03*/     SELECT * INTO IPL FROM CRICKET WHERE 1 = 2

/*9.2.04*/     INSERT INTO IPL SELECT * FROM CRICKET WHERE NAME LIKE '_A_____'

/*9.2.05*/     TRUNCATE TABLE IPL

/*9.2.06*/     DELETE FROM CRICKET WHERE CITY = 'JHARKHAND'

/*9.2.07*/     SP_RENAME 'IPL', 'IPL_2018'

/*9.2.08*/     DROP TABLE T20
