CREATE TABLE EMPLOYEE
(
	EID INT NOT NULL,
	ENAME VARCHAR(50) NOT NULL,
	DEPARTMENT VARCHAR(50) NOT NULL,
	SALARY DECIMAL(8,2) NOT NULL,
	JOININGDATE DATETIME NOT NULL,
	CITY VARCHAR(50) NOT NULL
)


INSERT INTO EMPLOYEE VALUES 
(101,'RAHUL','ADMIN',56000,'1990-01-01','RAJKOT'),
(102,'HARDIK','IT',18000,'1990-09-25','AHMEDABAD'),
(103,'BHAVIN','HR',25000,'1991-05-14','BARODA'),
(104,'BHOOMI','ADMIN',39000,'1991-02-08','RAJKOT'),
(105,'ROHIT','IT',17000,'1990-07-23','JAMNAGAR'),
(106,'PRIYA','IT',9000,'1990-10-18','AHMEDABAD'),
(107,'NEHA','HR',34000,'1991-12-25','RAJKOT')


/*8.01*/   SELECT MAX(SALARY) AS MAXIMUM, MIN(SALARY) AS MINIMUM, SUM(SALARY) AS TOTAL_SAL, AVG(SALARY) AS AVERAGE_SAL FROM EMPLOYEE

/*8.02*/   SELECT COUNT(EID) FROM EMPLOYEE

/*8.03*/   SELECT MAX(SALARY) FROM EMPLOYEE WHERE DEPARTMENT = 'IT'

/*8.04*/   SELECT COUNT(DISTINCT CITY) FROM EMPLOYEE

/*8.05*/   SELECT COUNT(EID), CITY FROM EMPLOYEE GROUP BY CITY

/*8.06*/   SELECT CITY FROM EMPLOYEE GROUP BY CITY HAVING COUNT(EID) > 1

/*8.07*/   SELECT SUM(SALARY), DEPARTMENT FROM EMPLOYEE GROUP BY DEPARTMENT

/*8.08*/   SELECT AVG(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT

/*8.09*/   SELECT MIN(SALARY) FROM EMPLOYEE WHERE CITY = 'AHMEDABAD'

/*8.10*/   SELECT SUM(SALARY), DEPARTMENT FROM EMPLOYEE WHERE CITY = 'RAJKOT' GROUP BY DEPARTMENT HAVING SUM(SALARY) > 50000

/*8.11*/   SELECT COUNT(EID) FROM EMPLOYEE WHERE CITY = 'RAJKOT'

/*8.12*/   SELECT MAX(SALARY) - MIN(SALARY) AS SAL_DIFFERENCE FROM EMPLOYEE

/*8.13*/   SELECT COUNT(EID) FROM EMPLOYEE WHERE JOININGDATE < '1991-01-01'

/*8.14*/   SELECT SUM(SALARY), DEPARTMENT FROM EMPLOYEE GROUP BY DEPARTMENT HAVING SUM(SALARY)>35000 ORDER BY SUM(SALARY)

/*8.15*/   SELECT COUNT(EID), DEPARTMENT FROM EMPLOYEE GROUP BY DEPARTMENT HAVING COUNT(EID) > 2

/*8.16*/   SELECT MIN(SALARY), CITY FROM EMPLOYEE GROUP BY CITY HAVING CITY = 'RAJKOT'

/*8.17*/   SELECT COUNT(EID) AS NUMBER_OF_EMPLOYEES, CITY FROM EMPLOYEE GROUP BY CITY

/*8.18*/   SELECT MIN(SALARY) AS MIN_SALARY, DEPARTMENT FROM EMPLOYEE GROUP BY DEPARTMENT

/*8.19*/   SELECT  SUM(SALARY) FROM EMPLOYEE GROUP BY CITY

/*8.20*/   SELECT MIN(SALARY) AS MIN_SALARY, MAX(SALARY) AS MAX_SALARY, SUM(SALARY) AS TOTAL_SALARY, DEPARTMENT FROM EMPLOYEE GROUP BY DEPARTMENT
